const tokens = {
  colors: {
    primary: '#000000',
    white: '#FFFFFF',
    transparent: 'transparent',
    brand: '#1ea7fd',
    surface: 'rgba(0,0,0,0.06)',
    border: 'rgba(0,0,0,0.10)',
    borderMd: 'rgba(0,0,0,0.18)',
    textPrimary: '#000000',
    textSecondary: '#333333',
    textMuted: '#666666',
    textHint: '#999999',
    danger: '#C0392B',
    warning: '#F59E0B',
    success: '#27AE60',
    info: '#2471A3',
    badgeHighBg: '#FEE2E2',
    badgeHighText: '#991B1B',
    badgeMedBg: '#FEF3C7',
    badgeMedText: '#92400E',
    badgeLowBg: '#DCFCE7',
    badgeLowText: '#166534',
    badgeCatBg: 'rgba(0,0,0,0.15)',
    badgeCatText: '#333333',
    successLight: '#e7fdd8',
    tipGreen: '#66bf3c',
  },
  typography: {
    fontSize: {
      display: 36,
      h1: 26,
      h2: 20,
      subhead: 15,
      body: 15,
      sm: 12,
      md: 14,
      lg: 16,
      xl: 32,
      caption: 12,
      label: 11,
      numeric: 28,
    },
  },
  fontWeights: {
    regular: '400',
    semibold: '600',
    bold: '700',
    extrabold: '800',
    black: '900',
  },
  fonts: {
    heading: 'AncizarSerif-Regular',
    headingItalic: 'AncizarSerif-Italic',
    headingBold: 'AncizarSerif-Bold',
    headingBoldItalic: 'AncizarSerif-BoldItalic',
    sub: 'Inter_400Regular',
    body: undefined,
  },
  spacing: {
    xs: 4,
    s: 6,
    sm: 8,
    smMd: 10,
    md: 12,
    mdLg: 15,
    lg: 16,
    lgMd: 20,
    xl: 24,
    xlMd: 30,
    xxl: 32,
    xxlMd: 40,
    xxxl: 48,
  },
  borderRadius: {
    sm: 6,
    md: 10,
    lg: 16,
    xl: 24,
    button: 48,
    pill: 100,
  },
  borderWidth: {
    hairline: 0.5,
    thin: 1,
  },
  button: {
    sm: {
      paddingVertical: 5,
      paddingHorizontal: 16,
      fontSize: 11,
    },
    md: {
      paddingVertical: 9,
      paddingHorizontal: 20,
      fontSize: 13,
    },
    lg: {
      paddingVertical: 12,
      paddingHorizontal: 24,
      fontSize: 16,
    },
  },
} as const;

export type Tokens = typeof tokens;

export default tokens;
