import type { Campaign } from '@/types/campaign';

const now = new Date().toISOString();

export const mockCampaigns: Campaign[] = [
  {
    _id: 'cmp_1',
    name: 'Summer VIP Outreach',
    templateId: 'tpl_monsoon',
    templateVariables: { Guest_Name: 'John' },
    type: 'manual',
    filters: {
      tier: 'Platinum',
      minPointsBalance: 50000,
    },
    recipientCount: 1450,
    status: 'draft',
    createdBy: 'Tanvir',
    createdAt: now,
    updatedAt: now,
    offerExpiry: '2026-08-01T00:00:00Z',
    metadata: {},
  },
  {
    _id: 'cmp_2',
    name: 'Post-Checkout Thank You',
    templateId: 'tpl_weekend',
    templateVariables: {},
    type: 'trigger',
    filters: {
      property: 'ABM Grand Hotel',
    },
    recipientCount: 0,
    status: 'pending_approval',
    createdBy: 'Tanvir',
    scheduledAt: '2026-07-01T10:00:00Z',
    createdAt: now,
    updatedAt: now,
    metadata: {},
  },
  {
    _id: 'cmp_3',
    name: 'Lapsed Guest Re-engagement',
    templateId: 'tpl_monsoon',
    templateVariables: { Guest_Name: 'Sarah' },
    type: 'scheduled',
    filters: {
      lapsedDays: 180,
    },
    recipientCount: 3200,
    status: 'approved',
    createdBy: 'Tanvir',
    approvedBy: 'usr_manager',
    scheduledAt: '2026-06-30T14:30:00Z',
    createdAt: now,
    updatedAt: now,
    metadata: {},
  },
  {
    _id: 'cmp_4',
    name: 'Gold Member Double Points',
    templateId: 'tpl_weekend',
    templateVariables: {},
    type: 'manual',
    filters: {
      tier: 'Gold',
    },
    recipientCount: 5600,
    status: 'sent',
    createdBy: 'Tanvir',
    approvedBy: 'usr_manager',
    scheduledAt: '2026-06-15T09:00:00Z',
    sentAt: '2026-06-15T09:00:05Z',
    createdAt: '2026-06-14T10:00:00Z',
    updatedAt: '2026-06-15T09:00:05Z',
    metadata: {},
  },
  {
    _id: 'cmp_5',
    name: 'Weekend Spa Promo',
    templateId: 'tpl_monsoon',
    templateVariables: { Guest_Name: 'Mike' },
    type: 'manual',
    filters: {
      property: 'ABM Resort Spa',
    },
    recipientCount: 890,
    status: 'sent',
    createdBy: 'Tanvir',
    approvedBy: 'usr_manager',
    scheduledAt: '2026-06-20T12:00:00Z',
    sentAt: '2026-06-20T12:00:02Z',
    createdAt: '2026-06-18T10:00:00Z',
    updatedAt: '2026-06-20T12:00:02Z',
    offerExpiry: '2026-07-01T00:00:00Z',
    metadata: {},
  },
];
